[package]
name = "jpez_scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

reqwest = {version = "0.11", features = ["blocking"]}
regex = "1"
scraper = "0.12.0"
chrono = "0.4"
divrem = "1.0"
