FROM alpine
# graphviz & ttf-dejavu are both plantuml dependencies that don't install automatically
RUN apk add graphviz ttf-dejavu plantuml

RUN mkdir build-docs

# Gathers only the dependencies of package.json so that docker npm install will only re-run on dependency change, not script change, etc.
ADD ./diagrams /diagrams
RUN plantuml /diagrams/db.puml -o/build-docs