FROM node:18
RUN npm install -g gatsby-cli

# Set CMD
EXPOSE 8080
CMD gatsby build && node --unhandled-rejections=strict server.js

# Get the node_modules
RUN mkdir -p /www/src
WORKDIR www
# node-init/package.json only contains dependencies, so will not uncache unless specifically dependencies are changed
COPY ./build/node-init/package.json /www/package.json
RUN npm install

# Add the rest
ADD . /www
