FROM postgres:15

EXPOSE 5432

ADD test-credentials credentials
# COPY ./src/db/db-dump-restore.sh /docker-entrypoint-initdb.d/00-db-dump-restore.sh
# COPY ./backup/postgres-dump.pgdata /docker-entrypoint-initdb.d/postgres-dump.pgdata
COPY ./src/db/db-creation.sql /docker-entrypoint-initdb.d/00-db-creation.sql