FROM alpine
RUN apk add jq moreutils
RUN mkdir node-init
WORKDIR node-init

# Gathers only the dependencies of package.json so that docker npm install will only re-run on dependency change, not script change, etc.
ADD package.json /node-init/package.json
RUN cat package.json | jq '{dependencies:.dependencies}' -S | sponge package.json