@startuml

object Users {
  **User_ID** : serial PK
  **Username**: varchar(30) PK2
  **Password_Hash**: char(60)
  Session_Token: char(128)
}

object Articles {
  **Article_ID**: smallserial PK
  **Title**: varchar(400)
  **Publish_Date**: date PK2
  **Placement**: smallint PK2
  **Content_Path**: varchar(200) PK3
  **Content_Length**: int
}

object ArticleKeywordLookups {
  **Article_Id**: FK(Articles(Article_ID)) PK
  **Keyword**: varchar(20) PK
  **Keyword_Count**: smallint
}

diamond diaArticleKeywordsOfLength
object ArticleKeywordsOfLength {
  **Article_ID**: FK(Articles(Article_ID)) PK
  **Keyword_Length**: Theoretical FK(\n  LENGTH(ArticleKeywordLookups.Keyword)\n  WHERE ArticleKeywordLookups.Article_ID = this.Article_ID\n) PK
  **Keywords_Count**: Computed(\n  SUM(ArticleKeywordLookups.Keyword_Count)\n  WHERE ArticleKeywordLookups.Article_ID = this.Article_ID\n  AND LENGTH(ArticleKeywordLookups.Keyword) = this.Keyword_Length\n) 
}

Users->Articles: Read Articles

Articles->ArticleKeywordLookups: Has Keyword Lookups
Articles-d-->diaArticleKeywordsOfLength: Has Number of Keywords of Length
diaArticleKeywordsOfLength-d->ArticleKeywordsOfLength
diaArticleKeywordsOfLength-u-->ArticleKeywordLookups: Has Sum Equal to\nnumber of Keywords with Keyword_Length\nthat correspond to Article_Id
@enduml